# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import *
import serial
from PyQt5 import QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import cv2
import os
import numpy as np
import time

arduino = serial.Serial('COM11', 9600)

class VideoThread(QThread):
    change_pixmap_signal = pyqtSignal(QImage)
    frame_captured = pyqtSignal(np.ndarray)

    def run(self):
        self.cap = cv2.VideoCapture(0)
        while True:
            ret, frame = self.cap.read()
            if ret:
                self.current_frame = frame.copy()
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                height, width, channel = frame.shape
                step = channel * width
                qimg = QImage(frame.data, width, height, step, QImage.Format_RGB888)
                self.change_pixmap_signal.emit(qimg)

    def stop(self):
        self.cap.release()
        self.quit()

    def capture_frame(self):
        return self.current_frame

class VideoWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        self.setWindowTitle("Camera Stream")
        self.layout = QVBoxLayout()
        self.label = QLabel(self)
        self.layout.addWidget(self.label)
        self.setLayout(self.layout)

    def update_image(self, qimg):
        self.label.setPixmap(QPixmap.fromImage(qimg))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(438, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.manualControlBtn = QtWidgets.QGroupBox(self.centralwidget)
        self.manualControlBtn.setGeometry(QtCore.QRect(10, 10, 421, 281))
        self.manualControlBtn.setObjectName("manualControlBtn")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.manualControlBtn)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 401, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.upBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.upBtn.setObjectName("upBtn")
        self.verticalLayout_2.addWidget(self.upBtn)
        self.downBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.downBtn.setObjectName("downBtn")
        self.verticalLayout_2.addWidget(self.downBtn)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rotateLeftBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rotateLeftBtn.setObjectName("rotateLeftBtn")
        self.verticalLayout_4.addWidget(self.rotateLeftBtn)
        self.rotateRightBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rotateRightBtn.setObjectName("rotateRightBtn")
        self.verticalLayout_4.addWidget(self.rotateRightBtn)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.manualControlBtn)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 399, 102))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.leftBtn.setObjectName("leftBtn")
        self.horizontalLayout.addWidget(self.leftBtn)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frontBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.frontBtn.setDefault(False)
        self.frontBtn.setObjectName("frontBtn")
        self.verticalLayout_3.addWidget(self.frontBtn)
        self.backBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.backBtn.setObjectName("backBtn")
        self.verticalLayout_3.addWidget(self.backBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.rightBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.rightBtn.setObjectName("rightBtn")
        self.horizontalLayout.addWidget(self.rightBtn)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.manualControlBtn)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 190, 101, 80))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.laserOnBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.laserOnBtn.setObjectName("laserOnBtn")
        self.verticalLayout_6.addWidget(self.laserOnBtn)
        self.laserOffBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.laserOffBtn.setObjectName("laserOffBtn")
        self.verticalLayout_6.addWidget(self.laserOffBtn)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.manualControlBtn)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(120, 190, 291, 80))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.disableMotorsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.disableMotorsBtn.setObjectName("disableMotorsBtn")
        self.verticalLayout_7.addWidget(self.disableMotorsBtn)
        self.enableMotorsBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.enableMotorsBtn.setObjectName("enableMotorsBtn")
        self.verticalLayout_7.addWidget(self.enableMotorsBtn)
        self.autoGB = QtWidgets.QGroupBox(self.centralwidget)
        self.autoGB.setGeometry(QtCore.QRect(10, 290, 421, 201))
        self.autoGB.setObjectName("autoGB")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.autoGB)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 401, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.homingBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.homingBtn.setObjectName("homingBtn")
        self.horizontalLayout_8.addWidget(self.homingBtn)
        self.homingLB = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.homingLB.setObjectName("homingLB")
        self.horizontalLayout_8.addWidget(self.homingLB)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 380, 401, 101))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scanBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.scanBtn.setObjectName("scanBtn")
        self.verticalLayout_5.addWidget(self.scanBtn)
        self.takePicBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.takePicBtn.setObjectName("takePicBtn")
        self.verticalLayout_5.addWidget(self.takePicBtn)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 438, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.leftBtn, self.rightBtn)
        MainWindow.setTabOrder(self.rightBtn, self.rotateLeftBtn)
        MainWindow.setTabOrder(self.rotateLeftBtn, self.rotateRightBtn)
    
        self.frontBtn.clicked.connect(self.front)
        self.backBtn.clicked.connect(self.back)
        self.leftBtn.clicked.connect(self.left)
        self.rightBtn.clicked.connect(self.right)
        self.upBtn.clicked.connect(self.up)
        self.downBtn.clicked.connect(self.down)
        self.rotateLeftBtn.clicked.connect(self.rotateLeft)
        self.rotateRightBtn.clicked.connect(self.rotateRight)
        self.homingBtn.clicked.connect(self.homing)
        self.scanBtn.clicked.connect(self.scan)
        self.takePicBtn.clicked.connect(self.takePic)
        self.laserOnBtn.clicked.connect(self.laserOn)
        self.laserOffBtn.clicked.connect(self.laserOff)
        self.disableMotorsBtn.clicked.connect(self.disable)
        self.enableMotorsBtn.clicked.connect(self.enable)

        # Add button to open video stream
        self.videoStreamBtn = QtWidgets.QPushButton(self.centralwidget)
        self.videoStreamBtn.setGeometry(QtCore.QRect(150, 500, 141, 31))
        self.videoStreamBtn.setObjectName("videoStreamBtn")
        self.videoStreamBtn.setText("Camera Stream")
        self.videoStreamBtn.clicked.connect(self.open_video_stream)

        # Initialize photo counter
        self.photo_counter = 1

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MedRADAR3D"))
        self.manualControlBtn.setTitle(_translate("MainWindow", "Control Manual"))
        self.upBtn.setText(_translate("MainWindow", "Sus"))
        self.downBtn.setText(_translate("MainWindow", "Jos"))
        self.rotateLeftBtn.setText(_translate("MainWindow", "Invarte Stanga"))
        self.rotateRightBtn.setText(_translate("MainWindow", "Invarte Dreapta"))
        self.leftBtn.setText(_translate("MainWindow", "Stanga"))
        self.frontBtn.setText(_translate("MainWindow", "Fata"))
        self.backBtn.setText(_translate("MainWindow", "Spate"))
        self.rightBtn.setText(_translate("MainWindow", "Dreapta"))
        self.laserOnBtn.setText(_translate("MainWindow", "Porneste Laser"))
        self.laserOffBtn.setText(_translate("MainWindow", "Opreste Laser"))
        self.disableMotorsBtn.setText(_translate("MainWindow", "Dezactiveaza Motoare"))
        self.enableMotorsBtn.setText(_translate("MainWindow", "Activeaza Motoare"))
        self.autoGB.setTitle(_translate("MainWindow", "Auto"))
        self.homingBtn.setText(_translate("MainWindow", "HOMING"))
        self.homingLB.setText(_translate("MainWindow", ""))
        self.scanBtn.setText(_translate("MainWindow", "SCANARE"))
        self.takePicBtn.setText(_translate("MainWindow", "Fa Poza!"))
        self.label.setText(_translate("MainWindow", ""))

    def front(self):
        arduino.write(b'1')
        
    def back(self):
        arduino.write(b'2')
    
    def left(self):
        arduino.write(b'3')

    def right(self):
        arduino.write(b'4')
    
    def up(self):
        arduino.write(b'5')
    
    def down(self):
        arduino.write(b'6')

    def rotateLeft(self):
        arduino.write(b'7')

    def rotateRight(self):
        arduino.write(b'8')
    
    def homing(self):
        arduino.write(b'9')

    def scan(self):
        arduino.write(b'A')

    def takePic(self):
        
        arduino.write(b'B')
        
        time.sleep(1.5) #0.5
        
        frame = self.video_thread.capture_frame()
        if frame is not None:
            filename = f"photo_{self.photo_counter}.jpg"
            cv2.imwrite(filename, frame)
            self.photo_counter += 1
        
        #time.sleep(0.5)
        
    
    def laserOn(self):
        arduino.write(b'C')

    def laserOff(self):
        arduino.write(b'D')
    
    def disable(self):
        arduino.write(b'E')

    def enable(self):
        arduino.write(b'F')

    def open_video_stream(self):
        self.video_window = VideoWindow()
        self.video_thread = VideoThread()
        self.video_thread.change_pixmap_signal.connect(self.video_window.update_image)
        self.video_thread.start()
        self.video_window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
